name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Esquema
          outputs: assets/github-snake.svg
          snake_color: "#00ffcc"
          background_color: "#0d1117"
          color_dots: "#6aff00,#ffcc00,#ff0077,#00ccff,#ffffff"

      - name: Commit and Push SVG
        run: |
          git config --global user.name "Esquema"
          git config --global user.email "esnotfound404@gmail.com"
          git add assets/github-snake.svg
          git commit -m "Update snake [skip ci]" || echo "No changes to commit"
          git push
